use call_center;

create table if not exists counselor(
	counselor_id int primary key auto_increment comment 'ID number of counselor'
    , counselor_first_name varchar(200) comment 'First name (given name) of the counselor'
    , counselor_last_name varchar(200) comment 'Last name (family name) of the counselor'
    , counselor_employment_type enum('volunteer', 'employee') comment 'The employment level of the counselor'
) comment 'Represents a employee or volunteer';

insert into counselor values
	(1,'Talbot','Walsh','employee')
	,(2,'Angela','Sprull','employee')
	,(3,'Darla','Chestnutt','volunteer')
	,(4,'Dusty','Leonida','employee')
	,(5,'Shana','Bullus','volunteer')
	,(6,'Fields','Heikkinen','employee')
	,(7,'Charleen','Willan','employee')
	,(8,'Aurelia','Hellis','volunteer')
	,(9,'Rebekah','Firby','employee')
	,(10,'Ingmar','Corzon','volunteer')
	,(11,'Miof mela','Pottell','employee')
	,(12,'Judd','MacIntyre','employee')
	,(13,'Whit','Tomei','employee')
	,(14,'Erina','Gawkroge','employee')
	,(15,'Kaylee','Baddiley','volunteer')
	,(16,'Glyn','Walklott','employee')
	,(17,'Lionello','Granleese','volunteer')
	,(18,'Addy','Hallick','volunteer')
	,(19,'Pernell','Thornbarrow','employee')
	,(20,'Scarlet','Finlator','volunteer')
	,(21,'Lisette','Payne','employee')
	,(22,'Martynne','Allington','volunteer')
	,(23,'Rossy','Sibille','employee')
	,(24,'Daron','Franzoli','volunteer')
	,(25,'Mable','Priddey','employee')
	,(26,'Debee','Sewter','volunteer')
	,(27,'Romain','Hunnable','employee')
	,(28,'Danie','Petrushanko','volunteer')
	,(29,'Sal','Medler','volunteer')
	,(30,'Shell','Girling','volunteer')
	,(31,'Polly','Keston','employee')
	,(32,'Berry','Beslier',null)
	,(33,'Kendricks','Aitken','volunteer')
	,(34,'Fenelia','Hurburt','employee')
	,(35,'Lucinda','Doorbar','volunteer')
	,(36,'Ellynn','Sowood','volunteer')
	,(37,'Hall','Gilkison',null)
	,(38,'Herbert','Muttock','volunteer')
	,(39,'Lauretta','Koppeck','volunteer')
	,(40,'Trudi','Fulger',null)
	,(41,'Costanza','Drinkhill','volunteer')
	,(42,'Evonne','Croyser','employee')
	,(43,'Minne','Ornelas','volunteer')
	,(44,'August','Ayce','volunteer')
	,(45,'Siobhan','McComas','volunteer')
	,(46,'Brigg','Moffet','employee')
	,(47,'Catarina','Grafhom','volunteer')
	,(48,'Moishe','Pyson','employee')
	,(49,'Ardenia','Grigaut','volunteer')
	,(50,'Chandra','Vlahos','volunteer')
;